name: Test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build with dotnet
      run: dotnet build

    - name: Run unit tests
      run: dotnet test --logger "console;verbosity=detailed";

    - name: Install resharper
      run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
    
    - name: Run resharper inspection
      run: jb inspectcode ConsoleApp1.sln /output=insreport.xml

    - name: Run resharper duplicate code check
      run: jb dupfinder ConsoleApp1.sln -o=dupreport.xml

    - name: Check Reports
      run: powershell ./resharper.ps1
