name: Limit complexity

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2

    - name: Use nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3

    - name: Build with dotnet
      run: dotnet build

    - name: Run unit tests
      run: dotnet test --logger "console;verbosity=detailed";

    - name: Generate coverage report
      run: dotnet test --collect:"XPlat Code Coverage"
      
    - name: Check Coverage
      run: powershell ./coverage.ps1 -linerate 0.95 -branchrate 0.8

