name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run echo
        run: echo "::set-output name=test::hello"
      
