name: Limit complexity

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2

    - name: Use nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3

    - name: Check Code Duplicacy
      run: |
<<<<<<< HEAD
        npm cache clean --force
=======
>>>>>>> c9c1d0bc37d9de27654ce1c25545e0bf39b007a2
        npm install -g jscpd
        npx jscpd /sender.Tests/*
