name: Test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build with dotnet
      run: dotnet build

    - name: Run unit tests
      run: dotnet test --logger "console;verbosity=detailed";

    - name: Generate coverage report
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Create coverage report
      run: dotnet reportgenerator "-reports:*Test*/TestResults/*/coverage.cobertura.xml" "-targetdir:CoverageReports" "-reporttypes:Html;Cobertura"
      
    - name: Check Coverage
      run: powershell ./sender.Tests/coverage.ps1 -linerate 0.95 -branchrate 0.8